export const LRU_CACHE_CONFIG = {
  DEFAULT_CAPACITY: 1000,
  DEFAULT_ID_LENGTH: 10,
};

export const DEFAULT_PORT = 3001;

export const LANG_CHAIN_SERVICE_OPTIONS = {
  MODEL: 'llama3',
  RECURSIVE_LIMIT: 1,
};
